name: tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [7.4, 8.0, 8.1]
        dependency-version: [ prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, exif
          coverage: pcov

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: |
          cp phpunit-coverage.dist.xml phpunit.xml
          vendor/bin/phpunit $( (( '${{ matrix.php }}' -ne '8.1' )) && printf %s '--exclude-group needsPhp81' )

      - name: Deploy coverage to codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: clover.xml
