name: tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'Apply fixes from StyleCI') }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [8.0, 8.1, 8.2]
        dependency-version: [ prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, exif
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.dependency-version }}-

      - name: Install dependencies
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: |
          cp phpunit-coverage.dist.xml phpunit.xml
          vendor/bin/phpunit $( [[ '${{ matrix.php }}' == '8.0' ]] && printf %s '--exclude-group needsPhp81' )

      - name: Deploy coverage to codacy
        if: matrix.php == '8.2'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: clover.xml
